### ISSUE TITLE
Do you have the following questions?

### ISSUE THREAD

**Issue by sugeladi** [Eonasdan/bootstrap-datetimepicker#1176]
TypeError: locale() locale ru is not loaded from moment locales!

 at Object.j.locale (http://localhost:9000/bower_components/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js:8:25442)
    at String.<anonymous> (http://localhost:9000/bower_components/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js:8:21712)
    at Function.jQuery.extend.each (http://localhost:9000/bower_components/jquery/dist/jquery.js:382:23)
    at Object.j.options (http://localhost:9000/bower_components/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js:8:21615)
    at c (http://localhost:9000/bower_components/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js:9:741)
    at HTMLDivElement.<anonymous> (http://localhost:9000/bower_components/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js:9:1113)
    at Function.jQuery.extend.each (http://localhost:9000/bower_components/jquery/dist/jquery.js:374:23)
    at jQuery.fn.jQuery.each (http://localhost:9000/bower_components/jquery/dist/jquery.js:139:17)
    at a.fn.datetimepicker (http://localhost:9000/bower_components/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js:9:983)
    at HTMLDocument.eval (eval at <anonymous> (http://localhost:9000/bower_components/jquery/dist/jquery.js:328:5), <anonymous>:2:33) <div ng-view="" class="ng-scope" data-ng-animate="1">(anonymous function) @ angular.js:12332$get @ angular.js:9111invokeLinkFn @ angular.js:8654nodeLinkFn @ angular.js:8152compositeLinkFn @ angular.js:7543publicLinkFn @ angular.js:7418$get.boundTranscludeFn @ angular.js:7562controllersBoundTransclude @ angular.js:8179update @ angular-route.js:934$get.Scope.$broadcast @ angular.js:16167(anonymous function) @ angular-route.js:617processQueue @ angular.js:14569(anonymous function) @ angular.js:14585$get.Scope.$eval @ angular.js:15848$get.Scope.$digest @ angular.js:15659$get.Scope.$apply @ angular.js:15953done @ angular.js:10366completeRequest @ angular.js:10538requestLoaded @ angular.js:10479

**Comment by sugeladi** [comment]
Need to refer to the following file：
    <script src="bower_components/moment/locale/ru.js"></script>
    <script src="bower_components/moment/min/moment-with-locales.js"></script>
